// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageThumbnail(arg1) {
  return window['go']['main']['App']['GetImageThumbnail'](arg1);
}

export function GetLastLogTime() {
  return window['go']['main']['App']['GetLastLogTime']();
}

export function GetNewestFileName(arg1) {
  return window['go']['main']['App']['GetNewestFileName'](arg1);
}

export function GetOutputFolderPath(arg1) {
  return window['go']['main']['App']['GetOutputFolderPath'](arg1);
}

export function GetWatcherDebugInfo() {
  return window['go']['main']['App']['GetWatcherDebugInfo']();
}

export function LoadNoticeLog() {
  return window['go']['main']['App']['LoadNoticeLog']();
}

export function LoadSetting() {
  return window['go']['main']['App']['LoadSetting']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function LogError(arg1, arg2) {
  return window['go']['main']['App']['LogError'](arg1, arg2);
}

export function LogInfo(arg1) {
  return window['go']['main']['App']['LogInfo'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFileInExplorer(arg1) {
  return window['go']['main']['App']['OpenFileInExplorer'](arg1);
}

export function OpenFolderSelectWindow() {
  return window['go']['main']['App']['OpenFolderSelectWindow']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function OutputConsoleLog(arg1) {
  return window['go']['main']['App']['OutputConsoleLog'](arg1);
}

export function OutputErrorLog(arg1, arg2) {
  return window['go']['main']['App']['OutputErrorLog'](arg1, arg2);
}

export function PingXSOverlay() {
  return window['go']['main']['App']['PingXSOverlay']();
}

export function ReadFile() {
  return window['go']['main']['App']['ReadFile']();
}

export function ResetOffset() {
  return window['go']['main']['App']['ResetOffset']();
}

export function SendNoticeLog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendNoticeLog'](arg1, arg2, arg3, arg4);
}

export function SendNoticeLogWithID(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendNoticeLogWithID'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateSetting(arg1) {
  return window['go']['main']['App']['UpdateSetting'](arg1);
}
