// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetNewestFileName(arg1:string):Promise<string>;

export function LoadSetting():Promise<main.SaveData>;

export function OpenFolderSelectWindow():Promise<string>;

export function OutputLog(arg1:string):Promise<void>;

export function PingXSOverlay():Promise<void>;

export function ReadFile():Promise<void>;

export function ResetOffset():Promise<void>;

export function UpdateSetting(arg1:Array<main.Setting>):Promise<void>;

export function WatchFile():Promise<void>;
