// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNewestFileName(arg1) {
  return window['go']['main']['App']['GetNewestFileName'](arg1);
}

export function LoadNoticeLog() {
  return window['go']['main']['App']['LoadNoticeLog']();
}

export function LoadSetting() {
  return window['go']['main']['App']['LoadSetting']();
}

export function OpenFolderSelectWindow() {
  return window['go']['main']['App']['OpenFolderSelectWindow']();
}

export function OutputConsoleLog(arg1) {
  return window['go']['main']['App']['OutputConsoleLog'](arg1);
}

export function PingXSOverlay() {
  return window['go']['main']['App']['PingXSOverlay']();
}

export function ReadFile() {
  return window['go']['main']['App']['ReadFile']();
}

export function ResetOffset() {
  return window['go']['main']['App']['ResetOffset']();
}

export function SendNoticeLog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendNoticeLog'](arg1, arg2, arg3, arg4);
}

export function UpdateSetting(arg1) {
  return window['go']['main']['App']['UpdateSetting'](arg1);
}
