// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNewestFileName(arg1) {
  return window['go']['main']['App']['GetNewestFileName'](arg1);
}

export function LoadSetting() {
  return window['go']['main']['App']['LoadSetting']();
}

export function OpenFolderSelectWindow() {
  return window['go']['main']['App']['OpenFolderSelectWindow']();
}

export function OutputLog(arg1) {
  return window['go']['main']['App']['OutputLog'](arg1);
}

export function PingXSOverlay() {
  return window['go']['main']['App']['PingXSOverlay']();
}

export function ReadFile() {
  return window['go']['main']['App']['ReadFile']();
}

export function ResetOffset() {
  return window['go']['main']['App']['ResetOffset']();
}

export function UpdateSetting(arg1) {
  return window['go']['main']['App']['UpdateSetting'](arg1);
}

export function WatchFile() {
  return window['go']['main']['App']['WatchFile']();
}
